doc/api.rst, drgn_tools/cmdline.py, tests/test_cmdline.py
=> Helper for cmdline

drgn_tools/block.py, drgn_tools/md.py
1. dump md.sb_flags out
2. dump bad blocks for underlying physical disks.
=> Two improvement to md helpers for better troubleshooting

drgn_tools/debuginfo.py
The module debuginfo code is already written to be careful with respect to module names that have hyphens and underscores. The filenames may not match the name that the kernel uses (e.g. filenames may contain hyphens, while the kernel's name contains underscores).
However, we were clearly not careful enough. When kernel module debuginfo is installed directly on the system, the loader did not search for the hyphenated version of module names with underscores. This led to missing debuginfo for modules like "dm_mod" (whose filename is dm-mod.ko.debug). Notably, the error did not occur on systems where drgn-tools extracts the RPM, since we take pains to rename all modules so their filename uses underscores instead of hyphens. The result is that this bug only really occurs when the debuginfo …
=> debuginfo: kernel modules with hyphen in filename

doc/api.rst, drgn_tools/ext4_dirlock.py, drgn_tools/lock.py, drgn_tools/locking.py, tests/test_lock.py
Adding helper for lock contention detection
=> Adding helper for lock contention detection

drgn_tools/block.py
- fix missing dump pending io from io scheduler
- warn user io from cfq will not be dumped
=> block: fix missing dump pending io from io scheduler

.gitignore, .gitlab-ci.yml, .pre-commit-config.yaml, drgn_tools/bt.py, drgn_tools/corelens.py, drgn_tools/debuginfo.py, drgn_tools/ext4_dirlock.py, drgn_tools/locking.py, drgn_tools/mounts.py, drgn_tools/workqueue.py, testing/requirements.txt, testing/vmcore.py, tests/conftest.py, tests/test_module.py, tox.ini
Sorry, these are three mostly unrelated commits. Two of them fix newly added vmcore test failures which are failing on main. The third one is an improvement for debuginfo downloaders -- I think I'm the only user of that right now anyway.
=> Two fixes and one improvement to debuginfo finders

drgn_tools/block.py, drgn_tools/ext4_dirlock.py, drgn_tools/locking.py, drgn_tools/util.py
- dump dispatched io from sq
- use crash style hung time for io pending
=> Block dump dispatched io for sq

drgn_tools/lsmod.py, drgn_tools/module.py
This is my patch on top of #33, it needs to be merged separately. The changes are:
1. Splitting out the interpretation of each `struct kernel_param` into a helper function `decode_param()` that does its best to give you the actual value of the parameter, as a drgn object.
2. On top of that, a function that allows you to lookup the dictionary of parameters for a module.
3. In addition, this implements the support for getting array parameter values and printing them in lsmod.
=> lsmod: split out parameter parsing to a helper

drgn_tools/scsi.py, tests/test_scsi.py
List scsi hosts
Authored-by: Gulam Mohamed <gulam.mohamed@oracle.com>
=> Add scsiinfo module

CHANGELOG.md, drgn_tools/corelens.py, setup.py, testing/requirements.txt
This adds one optimization for the CTF debuginfo loading in corelens, and also adds the code to release 0.7.0. We've made a lot of progress so I'd like to have an RPM available with the latest work!
=> Release 0.7.0

drgn_tools/slabinfo.py, tests/test_slabinfo.py
Prints slab cache information
Authored-by: Partha Satapathy <partha.satapathy@oracle.com>
=> Add slabinfo module

drgn_tools/partition.py, tests/test_partition.py
Prints partition information
Authored-by: Gulam Mohamed <gulam.mohamed@oracle.com>
Co-authored-by: Srivathsa Dara <srivathsa.d.dara@oracle.com>
=> Add partitioninfo module

drgn_tools/corelens.py, drgn_tools/module.py
These updates are mostly cosmetic, making things more pleasant for end users. See commit messages for details.
=> Corelens miscellaneous improvements

drgn_tools/cpuinfo.py
In the cpuinfo module, x86_get_cpu_info() will print a list of cpus for each NUMA node. However, in the current implementation, all CPU cores are considered as NUMA node0's CPUs and printed accordingly. This piece of information is incorrect when checking the CPU information for a vmcore produced by a multi-node server.
This commit fixes it by providing a x86_get_per_node_cpulist() function to retrieve per-node cpulists and using it in x86_get_cpu_info(). Tested for uek4,5,6,7.
=> cpuinfo: Fix the numa-to-cpulist parsing in x86_get_cpu_info()

drgn_tools/crash_net.py
Authored By: Praveen Kumar Kannoju<praveen.kannoju@oracle.com>
Co-Authored By: Srikanth C S<srikanth.c.s@oracle.com>
Co-Authored By: Shaleen Bathla<shaleen.bathla@oracle.com>
=> Add crash net module

drgn_tools/block.py, drgn_tools/dm.py, drgn_tools/md.py, drgn_tools/multipath.py, drgn_tools/util.py, tests/test_multipath.py
Add a drgn helper for multipath devices.
Add a test case for multipath drgn helper.
=> Add a drgn helper for multipath devices.

drgn_tools/bt.py, drgn_tools/lock.py
Authored-by: Partha Satapathy <partha.satapathy@oracle.com>
=> Add time and pid filters to locks. Print owner pid for mutex

CHANGELOG.md, buildrpm/python-drgn-tools.spec, man/corelens.1, setup.py
A few issues in the RPM / wheel packaging that I found on Friday.
=> Bugfix release 0.9.1

drgn_tools/task.py, tests/test_task.py
These helpers were added and reviewed when we were using internal repo for drgn-tools, but migration happened before these could be merged.
=> Task new helpers

drgn_tools/irq.py
v6.5 moved irq descriptors into a maple tree,
earlier they used to exist in a radix tree.
Change irq helpers to accomodate this change.
LSE-367.
=> LSE-367: irq: fix for v6.5 and later kernels.

drgn_tools/rds.py
Added new functions that display the rds send, retransmit and receive queues. Also added functions that display the MR list info for busy and clean lists.
=> rds_v2: Added str queues and rds_ib_mr info for busy/clean lists

drgn_tools/fsnotify.py
This is a tiny enhancement that I think would be worth including in v1, as it's a major quality of life improvement.
=> fsnotify: print time spent waiting for each task

Makefile
=> update TARGET in Makefile

drgn_tools/lock.py
V1 backport for #111
Orabug: 37186686
=> [v1] Lock improvements

drgn_tools/sysctl.py
add sysctl to corelens and cover more corner cases
=> corelens: sysctl: prints out sysctl entries

drgn_tools/kernfs_memcg.py
Remove slab_cache_is_merged check from kernfs_node iterator. When we iterate through kernfs_node slab-cache, we are looking for kernfs_node objects of specific types, for example cgroup, kobjects etc. This means we do some checks on obtained kernfs_node objects.
So rather than giving up in case of merged slab caches, we can still use the above mentioned checks to ensure that we are using correct kernfs_node object.
=> kernfs,memcg: remove merged slab cache check.

.github/workflows/litevm.yml, drgn_tools/corelens.py, drgn_tools/cpuinfo.py, drgn_tools/module.py, drgn_tools/rds.py
Each has a corresponding bug filed for it, see the commit descriptions.
This PR is against the main branch, another will be posted against `stable/v2.1.x`.
=> Fixes for issues found in QA testing

drgn_tools/util.py
=> percpu_ref: not crash with uninitialized refcount

drgn_tools/util.py
=> [2.1.x ] percpu_ref: not crash with uninitialized refcount

drgn_tools/bt.py
A simple enhancement to print panic bt.
=> Add corelens option to print panic bt

drgn_tools/workqueue.py
1. Allow for a workqueue name to be passed to show_all_workqueues, and in that case only show specified workqueue.
2. Make show_pwq handle the case of bad pwq addresses. This is useful on live systems.
=> workqueue: make some improvements in workqueue helper module.

drgn_tools/vectorinfo.py, tests/test_vectorinfo.py
Prints per-cpu and system vector information.
Authored-by: Partha Satapathy partha.satapathy@oracle.com
Co-authored-by: Srivathsa Dara srivathsa.d.dara@oracle.com
=> Add vectorinfo module
