oracle-samples/drgn-tools

.github/workflows/litevm.yml
Makefile
testing/README.md
testing/heavyvm/imgbuild.py
testing/heavyvm/runner.py
testing/litevm/vm.py
testing/util.py
testing/vmcore.py
tox.ini

This pull request incorporates several improvements for CI testing:
1. The tox environment names I established for Github Actions (`py3.6`, ...) don't seem to be correct. They need to have names like `py36` in order to work correctly. So, the first commit changes the names of these environments and makes the necessary changes for the Github Actions workflow to use those names instead. This makes Github Actions choose the correct Python version, and it also improves the very slow CI test runtimes we've seen on Gitlab CI.
2. Test output is very cluttered, and the test runner for Gitlab had the ability to split it into collapsible sections. I've added support to do this for Github too, and now the litevm test runner uses collapsible sections to help organize output.
3. I've been going …

Improvements for CI Testing

---

drgn_tools/corelens.py

With so much parallel development going on in drgn-tools, we're hitting a lot of conflicts around the list of modules which contain corelens modules.
I had wanted to avoid importing all of drgn_tools when I initially wrote this, since it seemed expensive and unnecessary given that most of the helpers didn't have corelens modules.
Now, it makes much more sense, since corelens modules are being written all the time. So let's avoid the merge conflicts, and just automatically import everything.

corelens: automatically import all modules

---

drgn_tools/block.py

When reading I/O requests out of a live kernel, there's a pretty good chance that the I/O could complete and the data structure could get freed during the time between when we found the data structure, and when we actually print it.
This means that the list iterators, and the printing functions, all risk reading stale and potentially overwritten data.
We can help reduce the chances of problems with two approaches:
1. Read the requests into a list ahead of time. This will help avoid the list iterators getting stale data.
2. Once we have all the requests, dereference the pointer and use .read_() to get a copy of the data that won't change even as the kernel memory changes.
With these two changes, the chance of reading false data is reduced (but not eliminated). It should reduce some …

block: Reduce the chance of inconsistency for inflight I/O

---

.gitlab-ci.yml
drgn_tools/mm.py
testing/vmcore.py
tests/test_mm.py

We've begun adding helpers which nominally support aarch64, and we're also being better about guarding our x86_64 specific code with architecture checks. This is good, but some of the older drgn-tools code still needed changes. The major thing here is adding the virtual memory map for aarch64, which underpins a lot of useful things like detecting whether an address is a module, text, data, direct-map, vmalloc, vmemmap, etc.
This PR makes those changes. I've added some vmcores to our vmcore test library which were generated on an aarch64 VM. The test suite passes on these vmcores!

drgn-tools: full aarch64 support

---

drgn_tools/dentry.py
drgn_tools/table.py
drgn_tools/util.py

We already have some excellent dentry helpers, but no actual corelens module. This PR adds the corelens module, and it adds a bit of optimization so that the runtime is pretty decent.
1. Add the corelens module.
2. Create a `dentry_path_any_mount()` helper to ensure we get a full path to the root for each dentry.
3. Stop loading dentries into memory when we're printing them out, this ensures we can scale to millions of dentries without any issue.
4. Try to match the `oled dentrycache` output by default.
5.  Improve performance by iterating over the dentry hash table in chunks, rather than one entry at a time.

Corelens module: dentrycache

---

doc/api.rst
drgn_tools/meminfo.py
tests/test_meminfo.py

This commit implements a meminfo corelens module that enables users to dump detailed statistics of the memory management subsystem. The output is similar to 'cat /proc/meminfo', which includes many aspects of the mm subsystem.
This module supports UEK 5, 6, and 7 and for both x86-64 and aarch64. It is tested for all these above settings. For each case, this meminfo module's output is compared against the output of `cat /proc/meminfo`. Results match closely with only small differences.

meminfo: Add meminfo corelens module

---

drgn_tools/mounts.py
tests/test_mounts.py

Added a module called mounts to corelens to display mountinfo from a given vmcore.

Added mounts module

---

drgn_tools/ext4_dirlock.py

It tells how many cached files under the dir, a small number doesn't mean iterating the dir will be fast, the size of the dir will be more accurate to tell that since ext4 may not release dir block even all files in that block were removed.

ext4_dirlock: show cached files under the dir

---

drgn_tools/buddyinfo.py
tests/test_buddyinfo.py

This commit implements buddyinfo corelens module that can dump details of each zone's buddy page allocator.
The output is similar to 'cat /proc/buddyinfo', which lists the number of free memory blocks at each order.
This module supports UEK 4, 5, 6, 7 for both x86 and aarch64. It is tested for these settings without crash.

buddyinfo: Add buddyinfo corelens module

---

drgn_tools/nfs_tools.py
drgn_tools/tests/test_nfs_tools.py
drgn_tools/util.py

Drgn helpers to display NFS and SUNRPC major data structures in vmcore or live system.
This initial version has support for NFS client-side only. NFS server-side support will be added in future enhancement.

nfs_tools: Helpers for NFS (client-side only) and SUNRPC subsystem.

---

drgn_tools/debuginfo.py

Path arguments to shutil.move are not allowed until Python 3.9.

debuginfo: Fix Python 3.6 compatibility

---

drgn_tools/block.py
tests/test_blockinfo.py

block-info prints scsihosts, scsi-device information and pending in-flight IOs
Authored-by: Gulam Mohamed <gulam.mohamed@oracle.com>
Co-authored-by: Srivathsa Dara <srivathsa.d.dara@oracle.com>

Add block-info module

---

drgn_tools/dm.py
tests/test_dm.py

The output is similar with 'dmshow' from crash-pykdump
```
>>> dm.show_dm(prog)
NUMBER  NAME                        MAPPED_DEVICE       FLAGS
dm-12   VGExaDb-LVDbOra1-real       0xffff940885630000  0x0
dm-6    VGExaDb-LVDbhome1           0xffff9551c7d30000  0x0
dm-11   VGExaDb-LVDoNotRemoveOrUse  0xffff9551c7ed0000  0x0
dm-7    VGExaDb-LVDblocal1          0xffff9551c7d80000  0x0
dm-1    VGExaDb-LVDbSys2            0xffff9551c7c40000  0x0
dm-8    VGExaDb-LVDbase1            0xffff9551c7df0000  0x0
dm-2    VGExaDb-LVDbSwap1           0xffff9551c7ca0000  0x0
dm-0    VGExaDb-LVDbSys1            0xffff9551c7c10000  0x0
dm-14   VGExaDb-LVDbOra1_snap       0xffff94fb16ca0000  0x0
dm-13   VGExaDb-LVDbOra1_snap-cow   0xffff941c1fa40000  0x0
dm-4    VGExaDb-LVDbgrid1           0xffff9551c7ce0000 …
```

dm: add helper to dump device mapper devices

---

drgn_tools/block.py
drgn_tools/dm.py

Here is an example of the output:
>>> dm.show_dm_table(prog)
ocivolume-oled: 0 20971520 linear 8:3 [sda3] 2048
ocivolume-root: 0 60940288 linear 8:3 [sda3] 20973568
I would like this gets reviewed/merged before multipath pull request, there were multiple generic dm helpers that can be reused by multipath helpers.
Only linear mapping is supported, i would like support multipath target after multipath helpers get merged, also i may add snapshot target support in future.

dm: add dmsetup table support for linear target

---

drgn_tools/debuginfo.py
drgn_tools/dentry.py
drgn_tools/file.py
drgn_tools/module.py
drgn_tools/table.py

This is a bit of a combination of changes which I believe are well explained in their commit messages, but going in order:
* A permissions fix for debuginfo extraction
* Add the filecache corelens command (the code already existed for much of it, just not the `CorelensModule` implementation)
* Address bad performance for `corelens` command on exadata - the `have_debuginfo()` function was quite slow.
* Fix a bug in type sizes.
* The `print_table()` function was printing a bunch of extra spaces at the end of wide tables, which wastes data and also results in the terminal "wrapping" table rows with blank lines.
* Reduced the default count for dentrycache to dump, this makes things a bit less bothersome when running on the CLI.

General fixes & improvements from recent development

---

drgn_tools/corelens.py
drgn_tools/smp.py

These are the corelens CLI tweaks we've been discussing at recent meetings:
- stop defaulting to /proc/kcore
- print usage when no arguments are given, "sysinfo" when just a vmcore is given
- automatically detect and load CTF if no DWARF debuginfo is available
- formatting fix
There's also newly added logic for determining whether modules should run:
- `skip_live` is used on corelens modules which are really only meant for vmcores, not live systems
- `run_when` can be set to three values:
- `always` in order to run in any report (`-a` or `-A`)
- `verbose` to only run in the verbose report (`-A)
- `never` if the module is only intended to be run manually via the CLI (e.g. `corelens /proc/kcore -M module`)

Corelens CLI updates

---

.header.txt
drgn_tools/bt.py
drgn_tools/debuginfo.py
drgn_tools/md.py
testing/rpm.py
testing/vmcore.py
tests/conftest.py
tests/test_block.py

The existing test frameworks don't give us a good opportunity to run tests against the version of drgn which was installed via RPM. Instead, they run tests against a version downloaded from PyPI.
This makes it difficult to run tests that use CTF, and especially difficult to run tests that are using the system CTF implementation from the drgn / binutils RPMs.
So, I'm adding a test runner that is designed to run directly on a OL system after installing the drgn RPM. Essentially, it should look like this:
```bash
sudo yum install -y path_to_drgn_with_ctf.rpm
python3 -m pip install --user 'pytest<7.1'
python3 -m testing.rpm --core-dir path/to/vmcores
```
The test runner doesn't use Tox, like the rest of our runners. This is probably for the best, and I think I will be getting rid of tox going …

Add test runner for testing installed drgn RPM

---

.gitlab-ci.yml
doc/api.rst
drgn_tools/dentry.py
drgn_tools/lsmod.py
drgn_tools/module.py
drgn_tools/partition.py
drgn_tools/slabinfo.py
drgn_tools/table.py

The partition info and slabinfo helpers had a couple small items that I wanted to address related to the docstrings and type annotations. I tweaked them and ensured that documentation builds successfully.
I also added two new table helpers: `Table` and `FixedTable`. Their docstrings should be self-explanatory, but the nice thing about them is that they can take care of the string formatting on your behalf, and they can also align individual columns to the left and right. By using `FixedTable`, you can also get output that is printed immediately, rather than all at once at the end of a loop. This is a major improvement for users, as it stinks to run a command and wait for a long time for a table to be output. To show the improvement, I moved the dentrycache helper to it, and the slabinfo …

Documentation updates, type annotation fixes, and new Table helpers

---

CHANGELOG.md
drgn_tools/bt.py
drgn_tools/corelens.py
drgn_tools/nvme.py
drgn_tools/task.py
drgn_tools/virtio.py
setup.py

Updates `bt` to skip zombie tasks, and adds some filtering logic for the `bt` corelens module which I think will be quite useful.
Relase 0.8.0 after that, for packaging up to our various environments.

Fix bt and release 0.8.0

---

drgn_tools/bt.py
drgn_tools/lock.py

Most of this relates to `bt_has()` which is used by the locking helpers. I added two improvements:
1. Indexing function calls for vmcores. This means that after the first `bt_has()` call, subsequent calls are basically free, since they use the index.
2. Creating a `bt_has_any()` API to allow searching for multiple functions at a time. This improves performance for live systems (though `bt_has()` is inherently a bad fit for live systems)...
3. Remove a duplicate call to `stack_trace()` as this incurs extra overhead

Some bt performance improvements

---

drgn_tools/task.py
tests/test_task.py

Allow passing pid | task | command to filter output by these. 
-k: display only kernel threads
-u: display only user threads
-G: display only the thread group leader

task: add more options to "ps" module

---

drgn_tools/block.py
drgn_tools/md.py

Couple fixes was added to make block and md helpers working better with upstream which will benefit future uek. Beside that one fix was adding "cpu" to inflight io output to help tell whether the cpu that request was issued from is in offline status.

couple fixes for block and md helpers

---

drgn_tools/crash_net.py
drgn_tools/meminfo.py
drgn_tools/virtutil.py

The virtutil module contained some test failures:
- UEK4 does not contain the `cpuhp_state` variable, handle it gracefully
- UEK6 CTF seems to omit the type for one variable, causing a KeyError. This is definitely a CTF bug (and from my initial investigation, appears to be a bug in CTF _generation_ not the drgn CTF code). Work around it here to ensure tests pass.
The net module was missing some changes that had been applied as part of the code review, introduce them here.

Fixes for recently merged helpers

---

drgn_tools/lock.py
drgn_tools/locking.py
drgn_tools/util.py

These changes add helpers for rwsem and osq locks.
Also change existing helpers when needed

locking: Add helpers for rwsem and osq locks

---

tests/test_mm.py

cpu_number has been merged into pcpu_hot object, for x86, in newer (v6.2+) kernels. For some archs like aarch64, it still exists as per-cpu variable.
Since we just need a per-cpu address for this test, use per-cpu runqueues. These have been existing as per-cpu varibale for long time and even if this changes in future the change will be architecture independent, so we would not have to worry about test passing for one arch and failing for other.
LSE-368.

LSE-368: tests: Fix test failures due to movement of cpu_number.

---

drgn_tools/workqueue.py
tests/test_workqueue.py

LSE-373: workqueue: Fix errors seen for newer (v6.4 and later) kernels.

---

.github/workflows/litevm.yml
drgn_tools/corelens.py
drgn_tools/debuginfo.py
drgn_tools/table.py
testing/litevm/rpm.py

There are three separate changes here, sorry. But each is small and easy to understand.
1. Add support for UEK-next, so corelens will run against it. Also add uek-next to the "lite VM" tests, but don't enable it yet because some tests fail. I've cataloged all the failures.
2. Get rid of caching in github actions, it doesn't save any time and it causes more failures.
3. Fix alignment of some tables.

Github actions fix, UEK-next support, and a table fix

---

drgn_tools/bt.py
drgn_tools/dentry.py
drgn_tools/fsnotify.py
drgn_tools/task.py
drgn_tools/util.py
tests/test_dentry.py
tests/test_fsnotify.py

- A corelens module "ls" for listing dentry children.
- A corelens module "fsnotify" for printing fsnotify info about every fanotify, inotify, and dnotify group.
- Some minor improvements to bt() in order to improve the fsnotify helper.

Add some VFS helpers

---

drgn_tools/meminfo.py

The Linux kernel calls total_swapcache_pages() to get the total number of in-used swap cache in pages. Within corelens.meminfo, this functionality is implemented by get_total_swap_cache_pages(). In the latest RHCK kernel on OL8 (v4.18.0-513.24.1.el8_9.x86_64), the kernel uses a per-node statistics item rather than iterating through the global array "swapper_spaces" to get the sum of pages, and it has optimization that makes array "nr_swapper_spaces" and "swapper_spaces" absent, causing crashes in corelens.
This fix checks whether "NR_SWAPCACHE" exists in the set of per-node statistics items. If found, the function directly reads and returns the counter. If not, it enters the iteration as the code did previously.

meminfo: fix get_total_swap_cache_pages() for RHCK

---

buildrpm/python-drgn-tools.spec
setup.py

Use the RPM name drgn-tools. Also, update the dependencies to allow 0.0.27 drgn versions, since we know these are compatible as well.

Update packaging based on discussions

---

.github/workflows/litevm.yml
testing/litevm/rpm.py
testing/litevm/vm.py

This reduces the total disk space required during each test, and avoids errors resulting from filling up the disk.

testing: litevm: remove RPM & extracted files after each test

---

drgn_tools/debuginfo.py

This is a branch to handle the change in uek-next version strings:
from: 6.8.0-2.el9uek.x86_64
to: 6.9.0-2.el9ueknext.x86_64
I did go ahead and make fixes for uek-next tests to allow them to pass. However, I've removed those to a branch which will not be part of the v1 milestone as they're not super important.

Fix parsing of uek-next versions for 6.9.0

---

drgn_tools/nfs_tools.py

This fix ensures the correct string representation of the bits in tk_runstate, which vary depending on the kernel version.

nfs_tools: fix problem of displaying string representation of tk_runsstate

---

CHANGELOG.md
buildrpm/python-drgn-tools.spec
drgn_tools/slabinfo.py
setup.py

The slabinfo fix was more involved than I wanted, but it works well, is compatible with drgn 0.0.25 - 0.0.27, and it actually makes the `slabinfo` module modestly faster.

A slabinfo fix, and the v1 (1.1.0) release

---

drgn_tools/slabinfo.py

We use a set to track the freelist, but we don't actually use it to check whether we've seen the object in the freelist. If an object gets double freed, we'll enter into an infinite loop.
Check this and raise an error. Since we're already detecting invalid freelist pointers as one kind of error, let's add an exception class hierarchy to represent freelist errors, and then we can put this into the slabinfo directly. Then, we can format the information in a table at the end of the slabinfo.

slabinfo: detect circular freelists

---

buildrpm/python-drgn-tools.spec

Users report that "dnf install drgn-tools" does not pull in the "drgn" package. On investigation, for OL8, the "Requires:" line must be place directly below the "%package" macro in order to apply to the drgn-tools package.
Orabug: 37126732

spec: Fix missing drgn dependency on OL8

---

buildrpm/python-drgn-tools.spec

Users report that "dnf install drgn-tools" does not pull in the "drgn" package. On investigation, for OL8, the "Requires:" line must be place directly below the "%package" macro in order to apply to the drgn-tools package.
Orabug: 37126783
For the main branch: #115.

[v1.x] spec: Fix missing drgn dependency on OL8

---

drgn_tools/slabinfo.py

We use a set to track the freelist, but we don't actually use it to check whether we've seen the object in the freelist. If an object gets double freed, we'll enter into an infinite loop.
Check this and raise an error. Since we're already detecting invalid freelist pointers as one kind of error, let's add an exception class hierarchy to represent freelist errors, and then we can put this into the slabinfo directly. Then, we can format the information in a table at the end of the slabinfo.
Orabug: 37170864
Main branch: #110

[v1.x] slabinfo: detect circular freelists

---

drgn_tools/dm.py

fix:
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/usr/lib/python3.6/site-packages/drgn_tools/dm.py", line 97, in show_dm
for dm, name, uuid in for_each_dm(prog):
File "/usr/lib/python3.6/site-packages/drgn_tools/dm.py", line 29, in for_each_dm_hash
yield hc.md, hc.name.string_().decode(), hc.uuid.string_().decode()
_drgn.FaultError: could not read memory from kdump: Cannot get page I/O address: PML4 table not present: pgd[0] = 0x0: 0x0

dm: handle NULL hc.uuid

---

drgn_tools/dentry.py
tests/test_dentry.py

Currently, ls module prints the dentries of a given directory. Add support to print the dentries of its subdirectories recursively up to a specified depth.
Signed-off-by: Srivathsa Dara <srivathsa.d.dara@oracle.com>

ls: Add support to recursively print dentries of subdirectories

---

drgn_tools/lock.py

One fix for mutexes, and then an enhancement to the printing for the locks, so that they print the symbol name or slab cache they came from. EG:
```
Scanning Mutexes...
Mutex: 0xffffffffc0e380a0 (object symbol: lockmod_mutex+0x0)
Mutex OWNER: lockmod-owner PID : 8933
Mutex WAITERS (Index, cpu, comm, pid, state, wait time (d hr:min:sec:ms)):
[1]: cpu: 0    lockmod-mutex_l  8934     D      0 00:00:06.761  
[2]: cpu: 0    lockmod-mutex_l  8935     D      0 00:00:06.761  
[3]: cpu: 0    lockmod-mutex_l  8936     D      0 00:00:06.761  
[4]: cpu: 0    lockmod-mutex_l  8937     D      0 00:00:06.761  
[5]: cpu: 0    lockmod-mutex_l  8938     D      0 00:00:06.761  
[6]: cpu: 0    lockmod-mutex_l  8939     D      0 00:00:06.761  
[7]: cpu: 0    lockmod-mutex_l  8940     S      0 00:00:06.761 …
```

Lock improvements

---

drgn_tools/block.py
drgn_tools/bt.py
drgn_tools/crash_net.py
drgn_tools/dentry.py
drgn_tools/device.py
drgn_tools/fsnotify.py
drgn_tools/lsmod.py
drgn_tools/module.py
drgn_tools/mounts.py
drgn_tools/numastat.py
drgn_tools/nvme.py
drgn_tools/partition.py
drgn_tools/scsi.py
drgn_tools/task.py
drgn_tools/virtio.py
drgn_tools/workqueue.py
testing/litevm/rpm.py
tests/test_mm.py
tests/test_module.py
tests/test_partition.py
tests/test_smp.py
tests/test_task.py

This pull request begins running the Github CI tests against UEK-next, which is currently at 6.11. It includes a whole crop of fixes to helpers that allow the tests to pass. This is the first version of UEK-next that I'm actually doing this for, so it includes a lot of changes from UEK7 era up till the present.
These fixes are are necessary, but almost certainly incomplete. The Github CI tests are very small QEMU VMs, and I did manually verify that the tests pass against my laptop as well. There are plenty of subsystems not exercised by my laptop or the limited VM in the CI tests.
I'm breaking these changes down into a few categories for which I believe subject matter experts should review. If you're tagged here, please take a look at the subset of changes mentioned (note the Git SHAs may …

UEK-NEXT support

---

drgn_tools/runq.py

Dump prio and runtime as well. Removed  min_run_time_seconds parameter since we have another lockup helper pending to merge.

runq: add prio and runtime

---

drgn_tools/block.py
drgn_tools/dm.py
drgn_tools/ext4_dirlock.py
drgn_tools/multipath.py
drgn_tools/util.py
tests/test_dm.py

The following are included in the patch set:
1. For dm table, adding multipath and snapshort support
2. New fields adding to blockinfo helpers to troubleshooting io hung with queue freezed
3. couple helpers to remove redundant code or fix small issues

Couple dm and IO enhancements

---

drgn_tools/kernfs_memcg.py
tests/test_kernfs_memcg.py

This as of now is just a dump of some of my bespoke debug scripts.

 kernfs_memcg: Add helpers to gather memcgroup related data

---

drgn_tools/block.py

commit 079a2e3e8625("blk-mq: Change shared sbitmap naming to shared tags") renamed "nr_active_requests_shared_sbitmap" to "nr_active_requests_shared_tags".
Orabug: 37393601

inflightIO: fix crash due to missing member

---

drgn_tools/lockup.py
tests/test_lockup.py

1. add helper for scanning potential lockups on cpus and dumping their info
2. add prio in runq dump

lockup: Print tasks which have been on-cpu for too long

---

drgn_tools/corelens.py
drgn_tools/dm.py
drgn_tools/ext4_dirlock.py
drgn_tools/nfs_tools.py
drgn_tools/rds.py

skip_unless_have_kmods can now take a list of modules as strings. Skip if any of the modules in the list are not present.

corelens: add support for multiple kmods in skip_unless_have_kmods

---

drgn_tools/kernfs_memcg.py

UEK4 (v4.1.x) kernel does not maintain separate counts for dying and active memcgroups, fix corresponding test failures with data available in UEK4.

kernfs,memcg: Fix CI failure for UEK4.

---

drgn_tools/kernfs_memcg.py
drgn_tools/sysctl.py
tests/test_kernfs_memcg.py

Two fixes to recent changes - one in the kernfs_memcg code, and one in the sysctl code. Both of these are only present in the `main` branch so no backport is required. Since they're fixes to such recent code, I haven't created a bug for them.

Fixes for CI failures

---

drgn_tools/iscsi.py
drgn_tools/scsi.py
tests/test_iscsi.py

Updated the helper based on feedback from @biger410

Add iscsi helpers to dump iscsi session information

---

drgn_tools/targetcli.py
tests/test_targetcli.py

Helper to reconstruct a targetcli-like structure and dump its iscsi and vhost sections info on iscsi target.

targetcli: dump iscsi and vhost info as in targetcli

---

buildrpm/python-drgn-tools.spec
setup.py

While the release version sounds very grand, this is simply the first official release of the 2.0 development cycle. This allows us to deploy packages and RPMs based on the development branch.

Release v2.0.0 (development release)

---

drgn_tools/workqueue.py
tests/test_workqueue.py

Add helper and corelens module to show unsubmitted pending works.
dealyed_work(s) get their pending bit set but are actually submitted to a workqueue,
upon expiration of corresponding timer(s).
Recently we have found some cases where a delayed work submitted to an already
offlined CPU was never getting executed, because underlying timers were not
firing in first place. Since the pending bit was set, this gave a notion that
work item was lost to workqueue subsystem (which was not the case here.)
Add an helper and a corelens module to dump delayed_work(s) whose timer has
not yet expired. This is off interest for offline CPUs mainly, because ideally
we should not see any delayed_work timer lying on an offlined CPU. So by default
the helper and corelens module dump this info for offlined CPUs …

helper and corelens module to show unsubmitted pending works.

---

drgn_tools/targetcli.py

Add portal numbers for each tpg.
Below is an example output:
```
o- iscsi
o- iqn.2003-01.org.linux-iscsi.richl-ol9-1.x8664:sn.3c63921d5d7b (struct iscsi_tiqn * 0xffff9fa703acf000)
o- tpgt_1 (struct se_portal_group 0xffff9fa7044b1020)
o- acls
o- iqn.1988-12.com.oracle:0a4e0f3bcde (struct se_node_acl * 0xffff9fa705301000)
o- mapped_luns
o- lun_0 (struct se_lun * 0xffff9fa70881a800) 
o- BACKSTORE: block_backend 
o- DEVICE: /dev/sda4
o- luns
o- lun_0 (struct se_lun * 0xffff9fa70881a800) 
o- BACKSTORE: block_backend 
o- DEVICE: /dev/sda4
o- portals
o- 0.0.0.0:3260
o- iqn.2003-01.org.linux-iscsi.richl-ol9-1.x8664:sn.c22b21e47243 (struct iscsi_tiqn * 0xffff9fa704c97000)
o- tpgt_1 (struct se_portal_group 0xffff9fa703984020)
o- acls
o- iqn.1988-12.com.oracle:0a4e0f3bcde (struct se_node_acl * …
```

targetcli: add portal info

---

.pre-commit-config.yaml
drgn_tools/deadlock.py
drgn_tools/lock.py

Deadlock Module
Created a dependency graph between Objects.
Tested with mutex cycle detection.
Lock Module
Changed scan_mutex_lock to return its findings for graph creating purpose

Deadlock detection

---

drgn_tools/lockup.py

Add a new feature in lockup to look for potential blocker (hogging a CPU for too long and RCU cannot go through) for process hang in RCU grace period

lockup: detect the blocker for process hang in RCU grace period

---

drgn_tools/iscsi.py
drgn_tools/scsi.py

Signed-off-by: Rajan Shanmugavelu <rajan.shanmugavelu@oracle.com

Update scsi host and added scsi devices with scsiinfo module

---

drgn_tools/debuginfo.py

On some distributions (e.g., Ubuntu), vmlinux may not reside in the modules directory. Search common locations for vmlinux, as referenced in: https://github.com/anakryiko/retsnoop/blob/389e2c9ddfc686ee048b063ce0c17b94b55398d2/src/retsnoop.c#L59-L67

debuginfo: Find vmlinux at other locations

---

.github/workflows/litevm.yml
buildrpm/python-drgn-tools.spec
setup.py

Stable branch backport for #173, and release it so we can support the latest drgn.

[stable] Support 0.0.32 & release 2.1.1-1

---

.github/workflows/litevm.yml
buildrpm/python-drgn-tools.spec
setup.py

The changes are small so we'll do basic testing and then add it to the allowable drgn-tools versions. We need this in order to release drgn because otherwise, 0.0.32 would break existing drgn-tools installs.

Add support for drgn 0.0.32

---

drgn_tools/memstate.py
drgn_tools/task.py
tests/conftest.py
tests/test_memstate.py

integrating memstate module into CoreLens.

Memstate Module

---

drgn_tools/rds.py

Added a new helper to extract and display detailed RDS QP state, including source/destination IPs. This enhances visibility into per-connection RDMA QP state via ib_connection traversal.

rds.py: Added RDS QP states diagnostics in rds helper

---

drgn_tools/rds.py

It seems that sometimes the task could be NULL, and in this case we should allow the module to continue executing.
Orabug: 38225228

rds: fix crash on NULL task

---

drgn_tools/rds.py

It seems that sometimes the task could be NULL, and in this case we should allow the module to continue executing.
Orabug: 38225232

[stable] rds: fix crash on NULL task

---

drgn_tools/pstack.py
drgn_tools/task.py
drgn_tools/util.py
tests/conftest.py
tests/test_pstack.py

This imports the pstack contrib script from drgn, and updates it. I'll end up pushing many of these updates back to drgn as well, but the main things are:
1. It is now tested on aarch64 and works with minimal changes.
2. Tasks that are running in user-mode on CPU can now be unwound and printed correctly.
3. Task state selection is done so that multiple pids, command patterns, or task states can be specified very flexibly.
4. For the "dump" mode, all task data is dumped to a single file, rather than several files per PID.

New corelens module: pstack

---

drgn_tools/dentry.py
drgn_tools/meminfo.py
drgn_tools/numastat.py
drgn_tools/printk.py

Three small fixes here. Two relate to string encoding and decoding. We've sometimes done a bit of unnecessary (or even harmful) `str.decode()` operations. Many kinds of data in the kernel (filenames, printk buffer) don't have guaranteed encodings, so decoding with the utf-8 encoding is not the right call. The right way is either to keep the data in `bytes` if possible, or else use `escape_ascii_string()` if we expect it to be text and we want to include it in text-mode/string output.
The last fix is for a change in 6.16 that has broken the test framework.

Small fixes
